name: symgrpmad
version: 1.0
summary: A game based upon the idea of overlapping symmetry groups.
description: This is a game based upon the idea of overlapping symmetry groups.  It is similar in nature to twisty puzzles such as Rubik's cube, but it takes place in the plane.
confinement: strict

apps:
  symgrpmad:
    command: env UBUNTU_MENUPROXY=0 desktop-launch $SNAP/bin/symgrpmad
    plugs: [home, x11, unity7]

parts:
  symgrpmad:
    plugin: scons
    source: https://github.com/spencerparkin/SymmetryGroupMadness.git
    source-branch: stable-release
    after: [desktop-gtk3]
